version: '2.2'
services:
    app:
        build: .
        working_dir: /usr/src/app
        ports:
            - 3000:3000
        command: npm run dev

    postgres:
        image: postgres:13
        restart: always
        ports:
            - '5432:5432'
        environment:
            POSTGRES_USER: raccoon
            POSTGRES_PASSWORD: test
            POSTGRES_DB: raccoon-db 
            TZ: Asia/Bangkok
        volumes:
            - pgdata:/var/lib/postgresql/data

volumes:   
  pgdata: